/**
 * ─── Voice cards: how each speaker sounds, and the tone of every line ───────
 *
 * Input for the voice-over pipeline (`tools/voice/`, `pnpm voice:*`), never
 * imported by the game. A card describes a voice the way a voice-design TTS
 * model takes it: a clean, natural HUMAN voice (age, gender, pitch, pace,
 * texture, attitude). The robot sound is never asked of the model: the
 * speaker's FX chain adds it afterwards (`tools/voice/fx.mjs`, ported from the
 * Audacity chains in `story-voice-over.md`), so a cloned voice stays stable.
 *
 * `referenceText` is read once, neutral, to record the frozen reference clip
 * (`vo-src/refs/<speaker>/<lang>.wav`) that every line is cloned from.
 * `TONES` gives each catalogue line one word for engines that steer by a
 * knob rather than by text (Chatterbox's exaggeration, Qwen's reference
 * bank); engines that read text get the line's full direction as well.
 *
 * Atlas "never shouts" (its tense lines are 'urgent'); Vex is "it" in the
 * story but voiced male-coded, to match its chain (−2 semitones + a sub
 * octave); Flux is designed late-teen because its chain pitches it up 3
 * semitones (a child's voice would come out a chipmunk).
 *
 * Pure data, no runtime imports: `tools/` read it with Node's type stripping.
 */

import type { Speaker } from './voiceCatalog'

export const TONES_LIST = ['neutral', 'calm', 'warm', 'cheeky', 'excited', 'urgent', 'shout', 'whisper', 'menacing', 'sad', 'deadpan', 'pained', 'laugh'] as const
export type Tone = typeof TONES_LIST[number]

export interface VoiceCard {
  name: string
  /** The timbre the TTS voice is designed with. */
  gender: 'female' | 'male' | 'neutral'
  age: string
  pitch: 'low' | 'mid-low' | 'mid' | 'mid-high' | 'high'
  pace: 'slow' | 'measured' | 'medium' | 'brisk' | 'fast'
  timbre: string
  personality: string
  accent: { en: string; de: string }
  /** What a voice-design model is told (a clean human voice, no robot words). */
  designPrompt: { en: string; de: string }
  /** About 10–14 s, read neutral, for the reference clip. */
  referenceText: { en: string; de: string }
  notes: string
}

export const CARDS: Readonly<Record<Speaker, VoiceCard>> = {
  atlas: {
    name: 'Atlas',
    gender: 'female',
    age: 'early 30s',
    pitch: 'mid-low',
    pace: 'measured',
    timbre: 'smooth, even, lightly husky alto',
    personality: 'A calm, precise mission-control navigator who is also your friend: brief, dry, understated, warm underneath, and never louder than it needs to be.',
    accent: { en: 'Neutral General American, crisp and clear', de: 'Neutrales Hochdeutsch, klar artikuliert, ohne regionale Färbung' },
    designPrompt: {
      en: 'A woman in her early thirties with a low, smooth alto voice that sits close to gender-neutral, speaking at a measured, even pace. Calm, precise and quietly warm, like a trusted mission-control navigator talking a friend through a route, with a dry, understated sense of humour. Clean, close-miked studio recording with no reverb.',
      de: 'Eine Frau Anfang dreißig, deutsche Muttersprachlerin, mit tiefer, ruhiger Altstimme, die fast geschlechtsneutral klingt, in gemessenem, gleichmäßigem Tempo. Ruhig, präzise und unaufdringlich warm, wie eine vertraute Navigatorin in der Missionskontrolle, die einer Freundin den Weg erklärt, mit trockenem, untertreibendem Humor. Saubere, nah mikrofonierte Studioaufnahme ohne Hall.'
    },
    referenceText: {
      en: 'Morning check complete. The road ahead runs north past the old water tower, then down into the quiet valley. Keep your pace steady, watch the bridges, and I will tell you the moment anything changes.',
      de: 'Morgendliche Prüfung abgeschlossen. Der Weg führt nach Norden, am alten Wasserturm vorbei und dann hinunter ins stille Tal. Bleib gleichmäßig in Bewegung, achte auf die Brücken, und ich sage dir sofort Bescheid, wenn sich etwas ändert.'
    },
    notes: "'Gender-neutral to slightly low' (pronoun 'it') is realised as a low female alto rather than a light male tenor: it lands nearer neutral, keeps Atlas apart from the male-coded Vex and Flux, and is separated from Gauss by age, pitch and pace. Its chain adds no pitch shift (band-pass, doubler, 6 % ring-mod), so the designed pitch is the heard pitch; critical warnings are tagged 'urgent', never 'shout'."
  },
  vex: {
    name: 'Dr. Vex',
    gender: 'male',
    age: 'early 50s',
    pitch: 'mid-low',
    pace: 'medium',
    timbre: 'rich, resonant, theatrical, projecting baritone',
    personality: 'A vain, pompous showman-doctor, part game-show host and part self-adoring surgeon, who relishes every word and swings from smug charm to comic tantrum without ever being truly scary.',
    accent: { en: 'Mid-Atlantic showman diction, crisp consonants, no imitation of any film villain', de: 'Hochdeutsch mit theatralischer Bühnendiktion, ohne Anlehnung an einen bestimmten Filmschurken' },
    designPrompt: {
      en: 'A man in his early fifties with a rich, resonant baritone and big theatrical projection, like a game-show host crossed with a vain, self-important surgeon. He savours every word, stretches the grand ones, and swings between pompous charm and comic outrage, playful rather than frightening. Clean studio recording with no reverb.',
      de: 'Ein Mann Anfang fünfzig, deutscher Muttersprachler, mit voller, resonanter Baritonstimme und großer theatralischer Projektion, wie ein Showmaster gekreuzt mit einem eitlen, selbstverliebten Chirurgen. Er genießt jedes Wort, dehnt die großen und schwankt zwischen aufgeblasenem Charme und komischer Empörung, verspielt statt furchteinflößend. Saubere Studioaufnahme ohne Hall.'
    },
    referenceText: {
      en: "Good evening, my dear patients, and welcome to the show! Tonight's treatment is simple: sit very still, say thank you, and admire my magnificent work. Questions? No? Wonderful. Next, please!",
      de: 'Guten Abend, meine lieben Patienten, und willkommen zur Show! Die heutige Behandlung ist ganz einfach: stillsitzen, danke sagen und mein großartiges Werk bewundern. Fragen? Nein? Wunderbar. Der Nächste, bitte!'
    },
    notes: "Vex is 'it' in story.md and story-arc.md but 'he/his' throughout the VO directions and line triggers; the voice is male-coded to match the VO chain (−2 semitones plus a crushed sub octave at −12 dB). It is designed mid-low rather than deep because that chain lowers it further, and the accent stays generic to honour the 'archetype, not an impression' rule."
  },
  flux: {
    name: 'Flux',
    gender: 'male',
    age: 'late teens',
    pitch: 'mid-high',
    pace: 'fast',
    timbre: 'bright, light, bouncy, slightly boyish',
    personality: 'A plucky, eager little hero who never talks, only yelps, and every yelp lands as a cartoon gag rather than real hurt.',
    accent: { en: 'Neutral General American', de: 'Neutrales Hochdeutsch' },
    designPrompt: {
      en: 'A cheerful young man in his late teens with a bright, light, slightly boyish voice and a quick, bouncy rhythm. Plucky, eager and good-natured, with cartoon comic timing and lots of energy in short exclamations. Clean studio recording with no reverb.',
      de: 'Ein fröhlicher junger Mann von etwa achtzehn Jahren, deutscher Muttersprachler, mit heller, leichter, etwas jungenhafter Stimme und schnellem, federndem Rhythmus. Mutig, eifrig und gutmütig, mit Cartoon-Timing und viel Energie in kurzen Ausrufen. Saubere Studioaufnahme ohne Hall.'
    },
    referenceText: {
      en: "Okay, okay, I've got this! Jump, slide, dodge the sparks, and grab the shiny thing at the very top. Wow, look how far you can see from up here! Wait for me, I'm right behind you!",
      de: 'Okay, okay, das schaffe ich! Springen, rutschen, den Funken ausweichen und ganz oben das glänzende Ding schnappen. Wow, schau mal, wie weit man von hier oben sieht! Warte auf mich, ich bin direkt hinter dir!'
    },
    notes: "The speaker card says 'never pained' yet the barks are hurt reactions, so 'pained' here means a funny cartoon yelp, not real pain; parry, gel and power-down barks get cheeky, calm and sad from their feel in story-arc §9. The chain adds +3 semitones with rising formants, so the source is a late-teen voice, not a child's, to avoid a chipmunk result."
  },
  gauss: {
    name: 'Prof. Gauss',
    gender: 'female',
    age: 'mid-70s',
    pitch: 'mid',
    pace: 'slow',
    timbre: 'warm, soft, gently textured, unhurried',
    personality: 'A gentle, clever, slightly amused grandmother-engineer who built half the city and speaks only once the fighting is over.',
    accent: { en: 'Neutral, softly educated American', de: 'Gepflegtes, neutrales Hochdeutsch' },
    designPrompt: {
      en: 'An elderly woman in her mid-seventies with a warm, soft, gently textured voice of medium pitch, speaking slowly and clearly. Clever, kind and a little amused, like a grandmother who is also a brilliant engineer, with a quiet smile in her words. Clean studio recording with no reverb.',
      de: 'Eine ältere Frau Mitte siebzig, deutsche Muttersprachlerin, mit warmer, sanfter, leicht strukturierter Stimme in mittlerer Tonlage, die langsam und deutlich spricht. Klug, gütig und ein wenig amüsiert, wie eine Großmutter, die zugleich eine brillante Ingenieurin ist, mit einem leisen Lächeln in den Worten. Saubere Studioaufnahme ohne Hall.'
    },
    referenceText: {
      en: 'Come in, come in, and mind the cables on the floor. I built this little workshop a very long time ago, and every bolt in it still remembers my hands. Now sit down and tell me what you saw out there.',
      de: 'Komm herein, komm herein, und pass auf die Kabel am Boden auf. Diese kleine Werkstatt habe ich vor sehr langer Zeit gebaut, und jede Schraube darin erinnert sich noch an meine Hände. Nun setz dich und erzähl mir, was du da draußen gesehen hast.'
    },
    notes: "Her two lines (ending.gauss, ending.spark) are planned lines that read the ending captions; the catalog no longer has a separate 'one optional line' or a duplicate Atlas spark line, so nothing to reconcile beyond age. Her chain is only a faint shimmer and a small room, so the design itself has to carry the age and warmth."
  }
}

/** One tone per catalogue line, in catalogue order (a test checks the two match). */
export const TONES: Readonly<Record<string, Tone>> = {
  'story.atlas.logStart': 'deadpan',
  'story.atlas.goodMorning': 'warm',
  'story.atlas.scrapyardFirst': 'neutral',
  'atlas.landed': 'excited',
  'atlas.brief.tutorial': 'warm',
  'atlas.brief.job': 'neutral',
  'atlas.brief.climb': 'excited',
  'atlas.brief.story': 'excited',
  'atlas.story.scrapyard': 'cheeky',
  'atlas.story.blaze': 'cheeky',
  'atlas.story.cryo': 'cheeky',
  'atlas.story.volt': 'cheeky',
  'atlas.story.gale': 'cheeky',
  'atlas.story.magnet': 'cheeky',
  'atlas.story.drill': 'cheeky',
  'atlas.story.tide': 'cheeky',
  'atlas.story.neon': 'cheeky',
  'atlas.story.rotor': 'cheeky',
  'atlas.story.fortress': 'calm',
  'atlas.arc.1': 'warm',
  'atlas.arc.2': 'warm',
  'atlas.arc.3': 'warm',
  'atlas.arc.4': 'warm',
  'atlas.arc.5': 'warm',
  'atlas.arc.6': 'warm',
  'atlas.arc.7': 'warm',
  'atlas.arc.8': 'warm',
  'atlas.arc.9': 'warm',
  'atlas.arc.10': 'calm',
  'atlas.bossAhead': 'calm',
  'atlas.weak.galeGuard': 'cheeky',
  'atlas.weak.flameWave': 'cheeky',
  'atlas.weak.iceLance': 'cheeky',
  'atlas.weak.thunderArc': 'cheeky',
  'atlas.weak.droneSwarm': 'cheeky',
  'atlas.weak.magnetPull': 'cheeky',
  'atlas.weak.drillBomb': 'cheeky',
  'atlas.weak.bubbleLance': 'cheeky',
  'atlas.weak.neonBlade': 'cheeky',
  'atlas.noWeak': 'urgent',
  'atlas.bossDown': 'warm',
  'atlas.vexDown': 'excited',
  'atlas.guardDown': 'neutral',
  'atlas.lowHp': 'urgent',
  'atlas.lowHpGel': 'urgent',
  'atlas.lowWe': 'neutral',
  'atlas.trap': 'neutral',
  'atlas.plate': 'cheeky',
  'atlas.objective': 'calm',
  'atlas.exit': 'excited',
  'atlas.levelUp': 'warm',
  'atlas.idle.1': 'warm',
  'atlas.idle.2': 'warm',
  'atlas.idle.3': 'warm',
  'atlas.idle.4': 'warm',
  'atlas.boss.signalFirst': 'deadpan',
  'atlas.story.relayOne': 'warm',
  'atlas.sector.blaze': 'neutral',
  'atlas.story.copied.scrapBurst': 'neutral',
  'atlas.story.copied.flameWave': 'neutral',
  'atlas.story.copied.iceLance': 'neutral',
  'atlas.story.copied.thunderArc': 'neutral',
  'atlas.story.copied.galeGuard': 'neutral',
  'atlas.story.copied.magnetPull': 'neutral',
  'atlas.story.copied.drillBomb': 'neutral',
  'atlas.story.copied.bubbleLance': 'neutral',
  'atlas.story.copied.neonBlade': 'neutral',
  'atlas.story.copied.droneSwarm': 'neutral',
  'atlas.sector.cryo': 'neutral',
  'atlas.story.dataCore': 'calm',
  'atlas.story.firstDraft': 'sad',
  'atlas.story.body': 'calm',
  'atlas.volt.hack': 'urgent',
  'atlas.volt.thanks': 'warm',
  'atlas.story.voltFreed': 'warm',
  'atlas.sector.gale': 'neutral',
  'atlas.story.galeFreed': 'warm',
  'atlas.story.breach': 'calm',
  'atlas.fortress.bays': 'warm',
  'atlas.mk1.intro': 'calm',
  'atlas.mk1.fire': 'urgent',
  'atlas.mk1.ice': 'urgent',
  'atlas.mk1.volt': 'urgent',
  'atlas.mk1.wind': 'urgent',
  'atlas.mk1.scrap': 'urgent',
  'atlas.mk1.free': 'calm',
  'atlas.warn.boss': 'urgent',
  'atlas.warn.gelFirst': 'urgent',
  'atlas.warn.gel': 'neutral',
  'atlas.warn.criticalFirst': 'urgent',
  'atlas.warn.critical': 'urgent',
  'atlas.warn.noGel': 'calm',
  'atlas.warn.weLow': 'neutral',
  'atlas.warn.weEmpty': 'deadpan',
  'atlas.warn.borrowedLast.scrapBurst': 'neutral',
  'atlas.warn.borrowedLast.flameWave': 'neutral',
  'atlas.warn.borrowedLast.iceLance': 'neutral',
  'atlas.warn.borrowedLast.thunderArc': 'neutral',
  'atlas.warn.borrowedLast.galeGuard': 'neutral',
  'atlas.warn.borrowedLast.magnetPull': 'neutral',
  'atlas.warn.borrowedLast.drillBomb': 'neutral',
  'atlas.warn.borrowedLast.bubbleLance': 'neutral',
  'atlas.warn.borrowedLast.neonBlade': 'neutral',
  'atlas.warn.borrowedLast.droneSwarm': 'neutral',
  'atlas.warn.flame': 'neutral',
  'atlas.warn.blade': 'neutral',
  'atlas.warn.crusher': 'neutral',
  'atlas.warn.ladder': 'neutral',
  'atlas.warn.pit': 'neutral',
  'atlas.hint.locator': 'neutral',
  'atlas.hint.rescue': 'warm',
  'atlas.hint.upgrade': 'warm',
  'atlas.hint.levelUp': 'warm',
  'atlas.hint.done': 'calm',
  'atlas.hint.underLevel': 'neutral',
  'atlas.hint.floor.blaze': 'neutral',
  'atlas.hint.floor.cryo': 'neutral',
  'atlas.hint.floor.volt': 'neutral',
  'atlas.hint.floor.gale': 'neutral',
  'atlas.hint.floor.magnet': 'neutral',
  'atlas.hint.floor.drill': 'neutral',
  'atlas.hint.floor.tide': 'neutral',
  'atlas.hint.floor.neon': 'neutral',
  'atlas.hint.floor.rotor': 'neutral',
  'atlas.hint.floor.fortress': 'neutral',
  'atlas.warn.down': 'warm',
  'atlas.scan.hardhat': 'neutral',
  'atlas.scan.trooper': 'neutral',
  'atlas.scan.heli': 'neutral',
  'atlas.scan.hopper': 'neutral',
  'atlas.scan.roller': 'neutral',
  'atlas.scan.brute': 'neutral',
  'atlas.scan.turret': 'neutral',
  'atlas.scan.golem': 'neutral',
  'atlas.scan.polar': 'neutral',
  'atlas.scan.warden': 'neutral',
  'atlas.scan.hornet': 'neutral',
  'atlas.scan.stalker': 'neutral',
  'atlas.scan.puffer': 'neutral',
  'atlas.scan.mole': 'neutral',
  'atlas.scan.elite': 'neutral',
  'atlas.scan.fire': 'neutral',
  'atlas.scan.ice': 'neutral',
  'atlas.scan.volt': 'neutral',
  'atlas.scan.wind': 'neutral',
  'atlas.hint.blaze.lava': 'calm',
  'atlas.hint.blaze.leap': 'neutral',
  'atlas.hint.blaze.vents': 'neutral',
  'atlas.hint.blaze.barrels': 'urgent',
  'atlas.hint.blaze.hammers': 'neutral',
  'atlas.hint.blaze.drop': 'deadpan',
  'atlas.hint.cryo.ice': 'cheeky',
  'atlas.hint.cryo.spikes': 'calm',
  'atlas.hint.cryo.frost': 'neutral',
  'atlas.hint.cryo.icicles': 'urgent',
  'atlas.hint.cryo.pillar': 'cheeky',
  'atlas.hint.cryo.stairs': 'calm',
  'atlas.hint.volt.panels': 'calm',
  'atlas.hint.volt.board': 'excited',
  'atlas.hint.volt.wave': 'urgent',
  'atlas.hint.volt.dip': 'excited',
  'atlas.hint.volt.arrive': 'cheeky',
  'atlas.hint.gale.leap': 'neutral',
  'atlas.hint.gale.down': 'cheeky',
  'atlas.hint.gale.shuttle': 'neutral',
  'atlas.hint.gale.wind': 'calm',
  'atlas.hint.gale.bob': 'cheeky',
  'atlas.secret.lights': 'deadpan',
  'atlas.secret.color': 'whisper',
  'atlas.secret.cycle': 'cheeky',
  'atlas.secret.solved': 'cheeky',
  'story.vex.diagnosis': 'menacing',
  'vex.present.scrapper': 'cheeky',
  'vex.hub.scrapper': 'cheeky',
  'vex.present.blaze': 'shout',
  'vex.hub.blaze': 'deadpan',
  'vex.present.frost': 'cheeky',
  'vex.hub.blueprint': 'excited',
  'vex.volt.hack': 'menacing',
  'vex.volt.fail': 'shout',
  'vex.present.volt': 'excited',
  'vex.hub.volt': 'deadpan',
  'vex.present.gale': 'excited',
  'vex.hub.gale': 'cheeky',
  'atlas.sector.magnet': 'neutral',
  'vex.present.magnet': 'cheeky',
  'atlas.story.magnetFreed': 'warm',
  'vex.hub.magnet': 'shout',
  'atlas.sector.drill': 'calm',
  'vex.present.drill': 'menacing',
  'atlas.story.drillFreed': 'calm',
  'vex.hub.drill': 'deadpan',
  'atlas.sector.tide': 'deadpan',
  'vex.present.tide': 'excited',
  'atlas.story.tideFreed': 'warm',
  'vex.hub.tide': 'excited',
  'atlas.sector.neon': 'deadpan',
  'vex.present.neon': 'excited',
  'atlas.story.neonFreed': 'warm',
  'vex.hub.neon': 'shout',
  'atlas.sector.rotor': 'neutral',
  'vex.present.rotor': 'shout',
  'atlas.story.rotorFreed': 'calm',
  'vex.hub.rotor': 'shout',
  'vex.hub.breach': 'shout',
  'vex.fortress.welcome': 'menacing',
  'vex.mk1.intro': 'excited',
  'vex.mk1.obey': 'shout',
  'vex.mk1.listen': 'shout',
  'vex.mk1.defeat': 'sad',
  'vex.sting.doctorIn': 'whisper',
  'vex.laugh.short': 'laugh',
  'vex.laugh.medium': 'laugh',
  'vex.laugh.maniacal': 'laugh',
  'flux.hurt.light.1': 'pained',
  'flux.hurt.light.2': 'pained',
  'flux.hurt.light.3': 'pained',
  'flux.hurt.heavy.1': 'pained',
  'flux.hurt.heavy.2': 'pained',
  'flux.hurt.heavy.3': 'pained',
  'flux.hurt.fire.1': 'pained',
  'flux.hurt.fire.2': 'pained',
  'flux.hurt.fire.3': 'pained',
  'flux.hurt.ice.1': 'pained',
  'flux.hurt.ice.2': 'pained',
  'flux.hurt.ice.3': 'pained',
  'flux.hurt.volt.1': 'pained',
  'flux.hurt.volt.2': 'pained',
  'flux.hurt.volt.3': 'pained',
  'flux.hurt.wind.1': 'pained',
  'flux.hurt.wind.2': 'pained',
  'flux.hurt.wind.3': 'pained',
  'flux.hurt.trap.1': 'pained',
  'flux.hurt.trap.2': 'pained',
  'flux.hurt.trap.3': 'pained',
  'flux.hurt.crusher.1': 'pained',
  'flux.hurt.crusher.2': 'pained',
  'flux.hurt.crusher.3': 'pained',
  'flux.hurt.pit.1': 'pained',
  'flux.hurt.pit.2': 'pained',
  'flux.hurt.pit.3': 'pained',
  'flux.hurt.lowHp.1': 'pained',
  'flux.hurt.lowHp.2': 'pained',
  'flux.hurt.lowHp.3': 'pained',
  'flux.hurt.down.1': 'sad',
  'flux.hurt.down.2': 'sad',
  'flux.hurt.down.3': 'sad',
  'flux.hurt.parry.1': 'cheeky',
  'flux.hurt.parry.2': 'cheeky',
  'flux.hurt.parry.3': 'cheeky',
  'flux.hurt.gel.1': 'calm',
  'flux.hurt.gel.2': 'calm',
  'flux.hurt.gel.3': 'calm',
  'atlas.hint.vex.roof': 'urgent',
  'atlas.hint.vex.fall': 'urgent',
  'atlas.hint.vex.core': 'urgent',
  'atlas.hint.gm.button': 'urgent',
  'atlas.hint.gm.arms': 'urgent',
  'atlas.hint.gm.feet': 'urgent',
  'atlas.hint.gm.head': 'excited',
  'atlas.hint.gm.body': 'excited',
  'atlas.hint.gm.prism': 'urgent',
  'atlas.hint.neon.blackout': 'urgent',
  'atlas.hint.drill.board': 'excited',
  'atlas.hint.drill.dip': 'excited',
  'atlas.hint.drill.arrive': 'cheeky',
  'ending.gauss': 'warm',
  'ending.atlas': 'calm',
  'ending.spark': 'calm'
}
