// `pnpm voice:cards` — prints the voice cards (src/game/audio/voiceCards.ts)
// as a readable sheet, voice-cards.md: who each speaker is as a voice, what a
// voice-design model is told, the reference text, and how their lines split
// by tone. Change a card in voiceCards.ts, then re-run this.

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CARDS, TONES, VOICE_LINES, ROOT } from './lib.mjs'

const rows = []
rows.push(`# Voice cards

Generated by \`pnpm voice:cards\` (tools/voice/cards.mjs) from
\`src/game/audio/voiceCards.ts\`. Do not edit by hand.

Each card is what a voice-design model is told to create: a clean, natural
human voice. The robot sound is added afterwards by the speaker's FX chain,
so the cloned voice stays stable. Every line is cloned from one frozen
reference clip per speaker and language (\`vo-src/refs/<speaker>/<lang>.wav\`),
read from the reference text below.
`)
for (const [id, c] of Object.entries(CARDS)) {
  const lines = VOICE_LINES.filter(l => l.speaker === id)
  const tones = {}
  for (const l of lines) tones[TONES[l.key]] = (tones[TONES[l.key]] ?? 0) + 1
  const split = Object.entries(tones).sort((a, b) => b[1] - a[1]).map(([t, n]) => `${t} ${n}`).join(', ')
  rows.push(`## ${c.name}

| Gender | Age | Pitch | Pace | Timbre |
| --- | --- | --- | --- | --- |
| ${c.gender} | ${c.age} | ${c.pitch} | ${c.pace} | ${c.timbre} |

${c.personality}

- **Accent:** ${c.accent.en} / ${c.accent.de}
- **Design prompt (EN):** ${c.designPrompt.en}
- **Design prompt (DE):** ${c.designPrompt.de}
- **Reference text (EN):** ${c.referenceText.en}
- **Reference text (DE):** ${c.referenceText.de}
- **Lines:** ${lines.length} (${split})
- **Notes:** ${c.notes}
`)
}
writeFileSync(join(ROOT, 'voice-cards.md'), rows.join('\n'))
console.log(`voice-cards.md: ${Object.keys(CARDS).length} cards, ${VOICE_LINES.length} lines`)
