// `pnpm voice:collect` — every voice line as a TTS job: its English and German
// text (params filled, then normalised for speech), who says it with that
// speaker's voice card, the stage direction, the situation, the tone, the
// longest it may run, and the file the game will read.
//
//   pnpm voice:collect              the lines the game speaks (live)
//   pnpm voice:collect --all        planned lines too (Vex, Flux, Gauss…)
//   pnpm voice:collect --samples    3 lines per language, for comparing engines
//   --lang en|de                    one language only
//
// Writes vo-src/jobs/<live|all|samples>.json (what `voice:gen` reads) and a
// readable .md beside it. A neutral line (barks, laughs) is English only:
// every language plays the English take.

import { mkdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { CARDS, LANGS, ROOT, SAMPLE_KEYS, TONES, VOICE_LINES, VO_SRC, VOICE_OUT, args, fileName, textOf } from './lib.mjs'
import { normalize } from './normalize.mjs'

/**
 * Respellings for a word the model keeps getting wrong in one line (by job
 * id): the model reads `say`, QA still checks the take against the real text.
 */
/** Lines whose text is broken on purpose (Vex stuttering "per-fect-ly"): a read-back cannot match it. */
const BROKEN = new Set(['vex.hub.volt'])

const SAY = {
  // "Relais" (French, [ʁəˈlɛː]) comes out "Zweiheles" in this two-word exclamation.
  'de/atlas_arc_2': 'Zwei Relä! Vex schmollt.',
  // Barks the model spells out as letters or pads with words: a pronounceable sound instead.
  ...Object.fromEntries([1, 2, 3].flatMap(n => [
    [`en/flux_hurt_lowHp_${n}`, 'Unnngh!'],
    [`en/flux_hurt_pit_${n}`, 'Whaaaaaa!'],
    [`en/flux_hurt_wind_${n}`, 'Whoa, whoa, whoa!']
  ])),
  'en/flux_hurt_ice_1': 'Brrrr!',
  'en/flux_hurt_ice_3': 'Brrrr! Zzt!'
}

const a = args()
const mode = a.samples ? 'samples' : a.all ? 'all' : 'live'
const langs = a.lang ? [a.lang] : LANGS
if (langs.some(l => !LANGS.includes(l))) throw new Error(`--lang must be one of ${LANGS.join(', ')}`)

const pick = mode === 'samples'
  ? SAMPLE_KEYS.map(k => VOICE_LINES.find(l => l.key === k) ?? (() => { throw new Error(`sample ${k} is not in the catalogue`) })())
  : VOICE_LINES.filter(l => mode === 'all' || l.status === 'live')

const jobs = []
const skipped = []
for (const line of pick) {
  for (const lang of langs) {
    const shown = textOf(line, lang)
    if (!shown) continue
    if (/\{\w+\}/.test(shown)) { skipped.push(`${lang} ${line.key}: unfilled ${shown.match(/\{\w+\}/)[0]}`); continue }
    const { text, emphasis } = normalize(shown, lang)
    const file = fileName(line.key)
    jobs.push({
      id: `${lang}/${file}`,
      key: line.key,
      file,
      lang,
      speaker: line.speaker,
      scene: line.scene,
      status: line.status,
      tone: TONES[line.key],
      max: line.max,
      shown,
      text,
      ...(SAY[`${lang}/${file}`] ? { say: SAY[`${lang}/${file}`] } : {}),
      // A sound, not words (barks, laughs), or a word broken on purpose: QA does not check it against the text.
      ...(line.neutral || BROKEN.has(line.key) ? { loose: true } : {}),
      emphasis,
      direction: line.direction[LANGS.indexOf(lang)],
      // For engines that take the direction as an English tag whatever the line's language.
      directionEn: line.direction[0],
      situation: line.when[LANGS.indexOf(lang)],
      out: relative(ROOT, join(VOICE_OUT, lang, `${file}.ogg`)).replaceAll('\\', '/')
    })
  }
}

const speakers = [...new Set(jobs.map(j => j.speaker))]
const doc = {
  mode,
  langs,
  cards: Object.fromEntries(speakers.map(s => [s, CARDS[s]])),
  jobs
}
const dir = join(VO_SRC, 'jobs')
mkdirSync(dir, { recursive: true })
writeFileSync(join(dir, `${mode}.json`), `${JSON.stringify(doc, null, 2)}\n`)

const cell = (s) => String(s).replaceAll('|', '\\|')
const md = [`# Voice jobs: ${mode}`, '', `Generated by \`pnpm voice:collect${mode === 'live' ? '' : ` --${mode}`}\`. ${jobs.length} jobs.`, '',
  '| Id | Speaker | Tone | Max s | Text for the model | Direction | Situation |', '| --- | --- | --- | --- | --- | --- | --- |',
  ...jobs.map(j => `| ${j.id} | ${j.speaker} | ${j.tone} | ${j.max} | ${cell(j.text)} | ${cell(j.direction)} | ${cell(j.situation)} |`)]
writeFileSync(join(dir, `${mode}.md`), `${md.join('\n')}\n`)

const per = langs.map(l => `${l} ${jobs.filter(j => j.lang === l).length}`).join(', ')
console.log(`vo-src/jobs/${mode}.json: ${jobs.length} jobs (${per}), speakers ${speakers.join(', ')}`)
for (const s of skipped) console.warn(`  skipped ${s}`)
