#!/usr/bin/env node
// ─── pnpm voice:script ───────────────────────────────────────────────────────
//
// Writes voice-todo.md: every line Atlas speaks in the game today, with the
// file name each recording must have, when it plays, and its English and
// German text (the recording script, e.g. for ElevenLabs). The lines and
// their notes come from the voice catalog (src/game/audio/voiceCatalog.ts),
// the text from the locale files, so re-run this after changing a line.
//
// Runs on Node's own TypeScript stripping (the locales and the line list are
// plain TS): `node --experimental-strip-types tools/voice-script.mjs`.

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const en = (await import(join(ROOT, 'src/i18n/locales/en.ts'))).default
const de = (await import(join(ROOT, 'src/i18n/locales/de.ts'))).default
const { VOICE_LINES, fileName } = await import(join(ROOT, 'src/game/audio/voiceCatalog.ts'))

const at = (o, key) => key.split('.').reduce((x, k) => x?.[k], o)
const fill = (s, params) => s.replace(/\{(\w+)\}/g, (m, n) => at(en, params?.[n] ?? '') ?? m)

// The lines in the game today, from the voice catalog (the full list, planned
// lines too, is `pnpm voice:report`).
const live = VOICE_LINES.filter(l => l.status === 'live')
const ids = live.map(l => l.key)
const WHEN = Object.fromEntries(live.map(l => [l.key, fill(l.when[0], l.params)]))
const cell = (s) => String(s ?? '—').replace(/\|/g, '\\|')
const rows = ids.map(id => `| \`${fileName(id)}.ogg\` | ${cell(WHEN[id])} | ${cell(at(en, id))} | ${cell(at(de, id))} |`)

const md = `# Voice-over — drop-in list (Atlas)

Generated by \`pnpm voice:script\` (tools/voice-script.mjs) from the locale
files: change a line there, then re-run this. Do not edit the table by hand.

Atlas is Flux's pocket-sized AI companion: warm, quick, a little cheeky. It
talks TO Flux. Every line is short (a speech bubble of 2–3 s).

- **Where:** \`public/audio/voice/en/<file>\` for English,
  \`public/audio/voice/de/<file>\` for German. File names exactly as below
  (the line's key with its dots as underscores + \`.ogg\`; \`.mp3\` /
  \`.m4a\` also work, \`.ogg\` wins if both exist).
- **Who hears what:** German players hear the German files; every other
  language hears the English ones. The speech bubble is always in the
  player's own language. A German line without a German file falls back to
  the English recording.
- **Missing files are fine.** The build lists the files that exist, so a
  line without one is never requested (no 404, nothing in the console); it
  just shows its bubble. A file that fails to decode is skipped silently.
- **Format:** mono, 44.1 kHz, about −16 LUFS, peaks under −3 dBFS, no
  leading silence (a line plays the moment its bubble pops), under ~3 s.
- **Timing:** the bubble stays up for the recording's length (+0.35 s).
- Picked up at build time; the dev server reloads by itself.

| File | Plays when | English | German |
| --- | --- | --- | --- |
${rows.join('\n')}
`
writeFileSync(join(ROOT, 'voice-todo.md'), md)
console.log(`voice-todo.md: ${ids.length} lines`)
