#!/usr/bin/env node
// ─── pnpm voice:script ───────────────────────────────────────────────────────
//
// Writes voice-todo.md: every line Atlas speaks in the game today, with the
// file name each recording must have, when it plays, and its English and
// German text (the recording script, e.g. for ElevenLabs). The lines and
// their notes come from the voice catalog (src/game/audio/voiceCatalog.ts),
// the text from the locale files, so re-run this after changing a line.
//
// Runs on Node's own TypeScript stripping (the locales and the line list are
// plain TS): `node --experimental-strip-types tools/voice-script.mjs`.

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const en = (await import(pathToFileURL(join(ROOT, 'src/i18n/locales/en.ts')).href)).default
const de = (await import(pathToFileURL(join(ROOT, 'src/i18n/locales/de.ts')).href)).default
const { VOICE_LINES, fileName } = await import(pathToFileURL(join(ROOT, 'src/game/audio/voiceCatalog.ts')).href)

const at = (o, key) => key.split('.').reduce((x, k) => x?.[k], o)
const fill = (s, params) => s.replace(/\{(\w+)\}/g, (m, n) => at(en, params?.[n] ?? '') ?? m)

// The lines in the game today, from the voice catalog (the full list, planned
// lines too, is `pnpm voice:report`).
const live = VOICE_LINES.filter(l => l.status === 'live')
const ids = live.map(l => l.key)
const WHEN = Object.fromEntries(live.map(l => [l.key, fill(l.when[0], l.params)]))
const cell = (s) => String(s ?? '—').replace(/\|/g, '\\|')
// A bark has no locale text: its yelp is the draft, the same in every language.
const text = (l, loc, i) => at(loc, l.key) ?? l.draft?.[i]
const rows = live.map(l => `| \`${fileName(l.key)}.ogg\` | ${cell(WHEN[l.key])} | ${cell(text(l, en, 0))} | ${cell(l.neutral ? '(English for all)' : text(l, de, 1))} |`)

const md = `# Voice-over — drop-in list

Generated by \`pnpm voice:script\` (tools/voice-script.mjs) from the locale
files: change a line there, then re-run this. Do not edit the table by hand.

Every line the game speaks: Atlas (Flux's AI companion: warm, quick, a
little cheeky), Dr. Vex's scenes, Flux's barks and the ending's captions.
Every line is short (a speech bubble of 2–3 s; a bark under a second).

- **Where:** \`public/audio/voice/en/<file>\` for English,
  \`public/audio/voice/de/<file>\` for German. File names exactly as below
  (the line's key with its dots as underscores + \`.ogg\`; \`.mp3\` /
  \`.m4a\` also work, \`.ogg\` wins if both exist).
- **Who hears what:** German players hear the German files; every other
  language hears the English ones. The speech bubble is always in the
  player's own language. A German line without a German file falls back to
  the English recording.
- **Missing files are fine.** The build lists the files that exist, so a
  line without one is never requested (no 404, nothing in the console); it
  just shows its bubble. A file that fails to decode is skipped silently.
- **Format:** mono, about −16 LUFS, peaks under −3 dBFS, no leading
  silence (a line plays the moment its bubble pops), under ~3 s. \`pnpm
  voice:gen\` writes them as Opus 24 kbps in an \`.ogg\` file (see
  story-voice-over.md, "The pipeline").
- **Timing:** the bubble stays up for the recording's length (+0.35 s).
- Picked up at build time; the dev server reloads by itself.

| File | Plays when | English | German |
| --- | --- | --- | --- |
${rows.join('\n')}
`
writeFileSync(join(ROOT, 'voice-todo.md'), md)
console.log(`voice-todo.md: ${ids.length} lines`)
